schema_version = "1.0.0"

id = "texture_manager"
version = "2.0.0"
name = "Texture File Path Editor"
tagline = "Manage, relink, gather and inspect all texture paths"
maintainer = "BHiMAX"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/BHiMAX/texture-manager"

[permissions]
files = "Reads and writes texture files from disk"
